### PR TITLE
Clarify that c_1 is a network parameter.

### LINKED ISSUE #471: Is c_1 trigerring liquidity auction network or market param?
From `0041-target-stake.md`: "If the LPs total committed stake is less than c_1 x target_stake we trigger liquidity auction... " and from `0035-liquidity-monitoring.md` "c1 - constant multiple for target stake triggering the commencement of liquidity auction." 

Is this a network or market parameter? IIRC *network*. 

If ppl agree we need to make the change at least in the above two files.

### PR DESCRIPTION
**Pull request by davidsiska-vega**
Closes #471  .

@gchaincl I think this is non-controversial following the Slack discussion - please merge if you're happy after reviewing this.

### CODE REVIEW

**Comment by qustavo** [comment]
Thanks, I created the **c<sub>1</sub>** constant as  `MarketLiquidityTargetStakeTriggeringRatio` network param, does that sound like a reasonable name?

**Comment by davidsiska-vega** [comment]
It sounds good. Maybe `MarketFirmLiquidityToTargetStakeTriggeringRatio`?

**Comment by qustavo** [comment]
out of curiosity, what's MarketFirm?

**Comment by davidsiska-vega** [comment]
It's `FirmLiquidity` i.e. what is underpinned by stake committed by LPs...  

... there can always be liquidity coming from limit orders that others place on the book... but we cannot rely on them staying.

**Comment by davidsiska-vega** [comment]
Ok... having read how exactly it's used again I propose we call it `SuppliedStakeToTargetStakeTriggerRatio`. Because that's what it is ;-).

**Comment by davidsiska-vega** [comment]
@gchaincl when you're happy approve the pull request and I'll merge.

**Review by qustavo — APPROVED** [review]

**Pull request merged**
