### PR TITLE
Define a party, mainly by linking to other specs

### LINKED ISSUE #424: What is a party
Make a spec

### PR DESCRIPTION
**Pull request by edd**
Closes #424

### CODE REVIEW

**Comment by edd** [comment]
@jeremyletang There's a section in here for 'Special parties'. Currently I'm only aware of 'network'

1. Does 'network' have a keypair? I think **No**
    1. If so, who has the private key
1. Is a transaction submitted to the chain on behalf of 'network'? I think **No**
    1. If it is, how is it signed?
1. Are there other special things we add in as 'parties'?
1. I have a vague memory of a '*' and a '!' appearing in some fields. Do they relate to special parties?

**Comment by davidsiska-vega** [comment]
@jeremyletang  I think this is "good enough" (TM) and "better than nothing" (TM).

**Comment by edd** [comment]
@jeremyletang are there any other 'special parties' like `network`? I think no.

**Comment by jeremyletang** [comment]
> @jeremyletang There's a section in here for 'Special parties'. Currently I'm only aware of 'network'
> 
>     1. Does 'network' have a keypair? I think **No**
>        
>        1. If so, who has the private key
> 
>     2. Is a transaction submitted to the chain on behalf of 'network'? I think **No**
>        
>        1. If it is, how is it signed?
> 
>     3. Are there other special things we add in as 'parties'?
> 
>     4. I have a vague memory of a '*' and a '!' appearing in some fields. Do they relate to special parties?

1. No
2. No
3. No
4. No (relate to accounts, it's only internals or at least should make sense only internally)

**Review by jeremyletang — APPROVED** [review]
Sounds good to me.
One thing that I'm not sure needs to be done there, but what should be the representation of a party via the API.

As of now we have a type:
```
Party {
   string ID;
}
```

Shoudl we simplify this an replace this type containing a single field (where actually ID is the public key of the party), by a simple string everywhere?

This would slightly simplify API, and even some places internally in the core.

Also I think that was briefly discussed somewhere already @edd @barnabee

**Comment by edd** [comment]
> This would slightly simplify API, and even some places internally in the core.
> Also I think that was briefly discussed somewhere already @edd @barnabee

That sounds good to me. Any objection @barnabee?

I don't think that changes anything in the spec, so now I have updated it to reflect the special party clarifications, let's merge.

**Pull request merged**
