### PR TITLE
Governance parameters

### LINKED ISSUE #292: Fix governance spec
As per Slack discussion here: https://vegaprotocol.slack.com/archives/CAHA5EX0F/p1591002479004100

each governance type should reference specific network parameters regarding proposal time and participation.

### PR DESCRIPTION
**Pull request by tamlyn10**

### CODE REVIEW

**Comment by edd** [comment]
@tamlyn10 I want to add acceptance criteria on the governance spec. Should I just continue this branch?

**Comment by tamlyn10** [comment]
This is all @barnabee now... I've exited this PR / spec... he's finishing it. Best check he's not got unmerged changes.

**Comment by barnabee** [comment]
I have unmnerged changes. Will push these after my 17:00 call.

**Comment by edd** [comment]
@barnabee It is after your call, please push

**Comment by jeremyletang** [comment]
@barnabee as @edd said.

**Comment by barnabee** [comment]
I have pushed updates now, sorry for the delay.

**Comment by tamlyn10** [comment]
@edd can we merge this?

**Pull request merged**
