### PR TITLE
Fractional order type spec

### LINKED ISSUE #469: Fractional orders
**Fractional order and position sizes (Needs a spec)**
  - Orders and positions can be fractional with a configurable by market number of decimal places
  - Validate order sizes are a non-zero multiple of the smallest increment (i.e. for a 4 decimal place market, a multiple of 0.0001)
  - Positions and margin work correctly with fractional orders
  - For engineeering: can be implemented with a decimal data type or uint[256?] same as for amounts

### PR DESCRIPTION
**Pull request by barnabee**
Add spec for fractional orders/positions and clarify where this may impact things.

### CODE REVIEW

**Review by edd — COMMENTED** [review]
Nice work so far on linking it all together. We need to expand the acceptance criteria in Orders but I think Fractional blah not having acceptance criteria itself makes sense

Assign this to me if you want me to do the acceptance criteria expansion

**Review by tamlyn10 — COMMENTED** [review]
This looks good to me!

**Comment by barnabee** [comment]
> Nice work so far on linking it all together. We need to expand the acceptance criteria in Orders but I think Fractional blah not having acceptance criteria itself makes sense
> 
> Assign this to me if you want me to do the acceptance criteria expansion

Re: orders, assuming what I think may happen does happen, and order sizes work like prices (i.e. they're always ints), I am not sure what the acceptance criteria would be. Or at least, the ACs here might be pretty implementation specific?

Assigned to you but if there's stuff you want me to do lmk and assign back.

**Review by jeremyletang — COMMENTED** [review]
This looks good overall. Do we want to add an hard limit in the specs for the DPD allowed by the system. e.g: maximum 6 DPD? Knowing that they will initially (maybe forever) be implemented with int64, having a decent limit would be useful.

**Comment by edd** [comment]
@barnabee back to you - I’ve done my minor edits. @jeremyletang has a question above.

**Review by edd — APPROVED** [review]

**Comment by davidsiska-vega** [comment]
I've added myself to review and potentially merge.

**Review by davidsiska-vega — APPROVED** [review]

**Pull request merged**
