### PR TITLE
Network parameters spec

### LINKED ISSUE #293: Network parameter spec
https://github.com/vegaprotocol/product/issues/292#issuecomment-636798841

### PR DESCRIPTION
**Pull request by tamlyn10**

### CODE REVIEW

**Comment by edd** [comment]
Good start! Things to add: 
- General network parameter *naming* convention
- Data formats available to network parameters (I have a feeling it's JSON as a string, string, number)

**Comment by edd** [comment]
@tamlyn10 please let me know how I can help move this along

**Comment by tamlyn10** [comment]
Slack thread [here](https://vegaprotocol.slack.com/archives/CAHA5EX0F/p1618568252281700). Assuming we agree with categories, I may need another pairing session with Edd, to finalise our naming convention accordingly (slated for Monday)

**Comment by tamlyn10** [comment]
Tamlyn's TODO list to finalise this:

- [ ] Add network parameters section to every spec file
- [ ] Check non-protocol specs for network parameters
- [ ] Add table of params as a spec file and retire spreadsheet
- [ ] Add table of market params
- [ ] Update governance file to refer to the new tables

**Comment by edd** [comment]
I’m slightly cheating here and merging early because I need to be back on #590. @tamlyn10 will continue with this in a new PR.

**Pull request merged**
