### PR TITLE
assets proposal

### PR DESCRIPTION
**Pull request by ashleyvega**
In GitLab by @jeremyletang on Mar 26, 2020, 17:40

### CODE REVIEW

**Comment by ashleyvega** [comment]
In GitLab by @jeremyletang on Mar 26, 2020, 18:05

changed title from **{-fist shot at -}assets proposal** to **assets proposal**

**Comment by Vegaklaus** [comment]
What is the format of the proposal ? Is there a proposal ID, or is every proposal its own ID ? In the former case, is it assured every validator  sees the same proposal ?

General: why is 'node' often used in singular ? Is it a typo or does that mean something specific ?


Line 19: Probably not a big issue, but can we be spammed with proposals ? Should verifiers only allow, say, 1 proposal per tokenholder per day ?

Line 21: Maybe more specify: "the validators verify" rather than "is verified". Is this functionality of the bridge to allow this verification or
coded elsewhere ?
Can the asset be invalidated in mid-vote, e.g., by spending the bitcoin after the first validators verified it ?

Line 22: Just to be sure, this means there's no no vote, just yes and abstain and wait for timeout ?

Line 24: One hour in blocktime ? Different validators might see it at different times, so one hour is not a clearly defined term. Maybe "x blocks after the first vote for that proposal on the blockchain" 
	
2+1/3 can be 2/3 rounded down + 1 (I suppose it means traitors+1, where the number of parties is 3*traitors+1)

Line 28: Is there a link to that ?
Line 32: More a question for the governance flow - the multisig is issues by the validators who confirm that the governance vote was yes ?

As all votes require only 1/3+2, it is possible to have two votes on the same asset that would succeed on independend subsets of the validators. 
Can that cause an issue (the same asset being used in two markets, the same asset being accepted twice for the same market,...) ?

**Comment by jeremyletang** [comment]
> What is the format of the proposal ? Is there a proposal ID, or is every proposal its own ID ? In the former case, is it assured every validator sees the same proposal ?

The proposal get an ID assigned and sequence just after going through consensus (as we are doing with he orders).

> General: why is 'node' often used in singular ? Is it a typo or does that mean something specific ?

A typo.

> Line 19: Probably not a big issue, but can we be spammed with proposals ? Should verifiers only allow, say, 1 proposal per tokenholder per day ?

Yes any rule required to reduce / stop spam can be implemented, but as the other parts of the system were spam is possible I just did not spend any though on that so far, and thought it could be done as part of some future work.

> Line 21: Maybe more specify: "the validators verify" rather than "is verified". Is this functionality of the bridge to allow this verification or
> coded elsewhere ?
> Can the asset be invalidated in mid-vote, e.g., by spending the bitcoin after the first validators verified it ?

We do not verify and asset as been deposit in here, but we verify the asset exist on the chain (meaning in case of an erc 20 token, that the contract for the token exisrts, and we can get information about it, and can use it).

> Line 22: Just to be sure, this means there's no no vote, just yes and abstain and wait for timeout ?

yes so far. but this can be changed if you require to.

> Line 24: One hour in blocktime ? Different validators might see it at different times, so one hour is not a clearly defined term. Maybe "x blocks after the first vote for that proposal on the blockchain"

Yes this is in blocktime speaking. it could be in term of block or anything, the existing proposal already use time not blocks for acceptance, so I reused that.

> 2+1/3 can be 2/3 rounded down + 1 (I suppose it means traitors+1, where the number of parties is 3*traitors+1)
> 
> Line 28: Is there a link to that ?

The specs as already been merged yes: https://github.com/vegaprotocol/product/blob/master/specs/0028-governance.md

> Line 32: More a question for the governance flow - the multisig is issues by the validators who confirm that the governance vote was yes ?

Well each node will issue a signature once the network governance vote is yes, then this can be agregated to be sent to the mutli sig verification on the bridge.

> As all votes require only 1/3+2, it is possible to have two votes on the same asset that would succeed on independend subsets of the validators.
> Can that cause an issue (the same asset being used in two markets, the same asset being accepted twice for the same market,...) ?

I'm not sure about that, I would imagine ideally at least 2+1 / 3 of the validator needs to accept the asset for the governance to work. to start with all nodes will need to validated it successfully.
A market can so far have 1 asset,  the market itself cannot accept twice something, the network should probably not  accept twice the same asset

**Comment by edd** [comment]
Transaction spam thoughts go here: https://github.com/vegaprotocol/product/issues/217

**Comment by Vegaklaus** [comment]
The lack of no-votes is not an issue, though the current voting allows two votes to succeed on independent sets of validators at the same time (each getting their own set of 2+t/3 voters). It's not clear to me if that is a problem (if the same asset is in two markets or two assets voted into one market), and how the governance flow would handle this.

One more question, the initial proposal is also submitted as a blockchain transaction ?

**Comment by edd** [comment]
@EVODelavega can probably answer this best (cc @jeremyletang)

**Comment by jeremyletang** [comment]
> The lack of no-votes is not an issue, though the current voting allows two votes to succeed on independent sets of validators at the same time (each getting their own set of 2+t/3 voters). It's not clear to me if that is a problem (if the same asset is in two markets or two assets voted into one market), and how the governance flow would handle this.

I'm not sure I understand this, so far we'll require all node to vote on favor of the asset, if even one node cannot validate the asset, and then not voting for it, the asset proposal will be stopped, and won't fo further (through the rest of the governance).

So far an asset could be use by multiple market for sure, also the definition of a market (market framework) do not allow two assets.

> One more question, the initial proposal is also submitted as a blockchain transaction ?

Yes, the proposal for a new asset is first submitted to the chain, so it get gossiped through the network, once the node have seen the transaction they then validate the asset exist on the foreign chainm and vote to accept it through the vega network.

**Comment by tamlyn10** [comment]
@C0deMunk33 have added you to this spec PR as an owner..

**Comment by tamlyn10** [comment]
What is status update on this spec, Jeremy, Danny?

**Comment by tamlyn10** [comment]
Implemented already. @jeremyletang to review the spec and merge etc.

**Pull request merged**
