### PR TITLE
Resolve "Prob weighted liquidity"

### LINKED ISSUE #213: Prob weighted liquidity
In GitLab by @davidsiska-vega on Feb 10, 2020, 15:36

### PR DESCRIPTION
**Pull request by ashleyvega**
In GitLab by @davidsiska-vega on Feb 10, 2020, 15:36

Closes #213

### CODE REVIEW

**Comment by ashleyvega** [comment]
In GitLab by @davidsiska-vega on Feb 10, 2020, 15:36

restored source branch `213-prob-weighted-liquidity`

**Comment by ashleyvega** [comment]
In GitLab by @davidsiska-vega on Feb 10, 2020, 15:39

added 1 commit

<ul><li>53904735 - Probability weighted liquidity spec start</li></ul>

[Compare with previous version](/vega-protocol/product/-/merge_requests/45/diffs?diff_id=74799676&start_sha=79188028b06bb19c8dca91cb672d40a94e6d5cf4)

**Comment by ashleyvega** [comment]
In GitLab by @davidsiska-vega on Feb 10, 2020, 16:33

added 1 commit

<ul><li>74dbf19f - Probability weighted liquidity spec progress</li></ul>

[Compare with previous version](/vega-protocol/product/-/merge_requests/45/diffs?diff_id=74812776&start_sha=53904735fcdb6176e85a6d00a0fc76d27c135d91)

**Comment by ashleyvega** [comment]
In GitLab by @davidsiska-vega on Feb 10, 2020, 16:53

added 1 commit

<ul><li>acb2acce - Probability weighted liquidity spec fix typos</li></ul>

[Compare with previous version](/vega-protocol/product/-/merge_requests/45/diffs?diff_id=74816013&start_sha=74dbf19ff3182f88996caa4937d700cd6138ed99)

**Comment by ashleyvega** [comment]
In GitLab by @davidsiska-vega on Feb 10, 2020, 16:56

added 1 commit

<ul><li>c9c141c6 - Probability weighted liquidity spec fix typos</li></ul>

[Compare with previous version](/vega-protocol/product/-/merge_requests/45/diffs?diff_id=74816553&start_sha=acb2acce5019009e3c2d6193932ccf2d6a353280)

**Comment by davidsiska-vega** [comment]
I think this is ready to be merged I've gone over this with @witgaw yesterday. I propose that @tamlyn10 reads it and then we get someone from Engineering to have a look.

**Comment by tamlyn10** [comment]
Thanks, I'll have a look today!

**Comment by tamlyn10** [comment]
@davidsiska-vega I think this looks OK to me, but I suggest it gets review by engineering as it's quite a "mathsy" spec , so just to clarify the notation etc. makes sense.

**Review by tamlyn10 — APPROVED** [review]

**Pull request merged**
