### PR TITLE
Sweetwater++ scope file

### LINKED ISSUE #701: Create 💦 SweetWater++ milestone definition document
In order for everyone in Vega to understand the scope of the requirements for 💦 SweetWater++ we need a milestone definition document detailing:

- priority
- features included (with links to find project boards and specs)
- why these features have been included
- the owner of the feature

### PR DESCRIPTION
**Pull request by edd**
closes #701

### CODE REVIEW

**Comment by edd** [comment]
@gordsport how is this looking?

**Comment by gordsport** [comment]
Hey @edd,
I have added some more to this file. I think it's at the point where we need specs to be merged/created.
I will watch the PRs and update this file as they get merged

**Review by gordsport — APPROVED** [review]
This now reflects the updates in the priority meeting. And can be merged so that everyone can see it

**Comment by gordsport** [comment]
Merging post the protocol design meeting.

Changes to links still to come as they are ready.

Any priority / scope changes to go through a formal review

**Pull request merged**
