### PR TITLE
Rename files to include codes

### LINKED ISSUE #780: Add [0000]-[SHORTNAME] to all spec filenames

### PR DESCRIPTION
**Pull request by edd**
First stab. All filenames are being renamed so that they have a unique ID based on their sequence (4 digit ID, unchanged) and a short, hopefully representative enough code.

Initially I started making it: `([0-9]{4})-([A-Z]{6})+` so that the text portion had to be 6
characters, but then I changed it to be a looser `([0-9]{4})-([A-Z])+` to allow a more expressive text portion, given that the point of adding this text code is to make it referenceable and make sense for humans. Do we accomplish that? If you saw a test refer to `0038-ORDERLIQ-02` would you know it meant Acceptance Criteria 2 on
the Liquidity Order spec?

- Rename all files

Closes #780

### CODE REVIEW

**Comment by edd** [comment]
The current status leavs us with this:
```
0001-MKTFW - market-framework.md
0002-STTLMNT - settlement.md
0003-MTMKT - mark-to-market-settlement.md
0004-AMENDS - amends.md
0005-COLLAT - collateral.md
0006-POSITIONS - positions-core.md
0007-POSITIONSNC - non-core-positions-api.md
0008-TRADING - trading-workflow.md
0009-MARKPRICE - mark-price.md
0010-MARGIN - margin-orchestration.md
0011-MARGALLOC - check-order-allocate-margin.md
0012-POSRES - position-resolution.md
0013-ACCNTS - accounts.md
0014-ORDERTYPES - order-types.md
0015-INSURAPOOL - market-insurance-pool-collateral.md
0016-PRODFUT - product-builtin-future.md
0017-PARYT - party.md
0018-RISKMODEL - quant-risk-models.ipynb
0019-MARGINCALC - margin-calculator.md
0020-APIS - core-api.md
0021-MKTDATA - market-data-spec.md
0023-CALIBR - calibrators.md
0024-ORDERSTATUS - order-status.md
0025-ORDERCREATION - order-submission.md
0026-AUCTION - auctions.md
0027-ASSETCREATION - asset-proposal.md
0028-GOVERNANCE - governance.md
0029-FEES - fees.md
0030-ETHMULTISIG - multisig_control_spec.md
0031-ETHBRIDGE - ethereum-bridge-spec.md
0032-PRICEMONITOR - price-monitoring.md
0033-ORDERCANCEL - cancel-orders.md
0034-AUTH - auth.md
0035-LIQMON - liquidity-monitoring.md
0035-prob-weighted-liquidity-measure.ipynb
0036-BRIDGEEVENTS - event-queue.md
0037-ORDERPEG - pegged-orders.md
0038-ORDERLIQ - liquidity-provision-order-type.md
0039-MKTDEPTH - market-depth-calculation.md
0040-ASSETFW - asset-framework.md
0041-TARGETSTAKE - target-stake.md
0042-LIQFEES - setting-fees-and-rewarding-lps.md
0043-market-lifecycle-flow-diagram.graffle
0043-market-lifecycle-flow-diagram.svg
0043-MKTLIFECYCLE - market-lifecycle.md
0044-LIQMECHANICS - lp-mechanics.md
0045-DATASRC - data-sourcing.md
0046-DATASRCMSG - data-source-signed-message.md
0047-DATASRCFILT - data-source-filter.md
0048-DATASRCINTERNAL - data-source-internal.md
0049-TXVALIDATION - validate-transaction-preconsensus.md
0050-EPOCHS - epochs.md
0051-PRODUCT - product.md
0052-FRACPOS - fractional-orders-positions.md
0053-PRODPERP - product-builtin-perpetual-future.md
0054-NETPARAM - network-parameters.md
0055-on-chain-treasury-draft-sketch.jpg
0055-TREASURY - on-chain-treasury.md
0056-REWARD - rewards-overview.md
0057-REWARDFUNC - reward-functions.md
0058-REWARDSIM - simple-POS-rewards.md
0059-STAKING - simple-staking-and-delegating.md
0060-WENDY - Wendy.md
0061-REWARDPOS - simple-POS-rewards-SweetWater.md
0062-SPAM - spam-protection.md
0063-VALKEYS - validator-vega-master-keys.md
0064-VALPERF - validator-performance-based-rewards.md
0065-FLOAT - floating-point-consensus.md
0065-VALWEIGHTTM - validator-tendermint-weights.md
0066-KEYS - KeyManagement.md
```

**Comment by davidsiska-vega** [comment]
*not-blocking* Can we possible get rid of the whitespaces in the filenames? I am old and don't trust whitespace / I don't like it on command line because all the escape character usage it forces.

**Comment by edd** [comment]
Removing whitespace is fine. You and @witgaw have voted for that, so - it can be done. 

What I'm stuck on is a sensible system for generating the text portion of the ID. @jeremyletang wants them all to be the same length. I think that makes them unclear (`FEES` is our shortest one, but 4 characters is hard to express `PRICEMONITORING` - and if it's hard to communicate what it is, isn't the whole exercise pointless?


```
([0-9]{4})-([A-Z]{4})-([a-z_]*).md
```

is where I'm at currently:

```
0001-MKTF-market_framework.md
0002-STTL-settlement.md
...
0065-VALW-validator_tendermint_weights.md
```

**Comment by edd** [comment]
```
0001-MKTF-market_framework.md
0002-STTL-settlement.md
0003-MTMK-mark_to_market_settlement.md
0004-AMND-amends.md
0005-COLL-collateral.md
0006-POSI-positions_core.md
0007-POSN-non_core_positions_api.md
0008-TRAD-trading_workflow.md
0009-MRKP-mark_price.md
0010-MARG-margin_orchestration.md
0011-MARA-check_order_allocate_margin.md
0012-POSR-position_resolution.md
0013-ACCT-accounts.md
0014-ORDT-order_types.md
0015-INSR-market_insurance_pool_collateral.md
0016-PFUT-product_builtin_future.md
0017-PART-party.md
0018-RSKM-quant_risk_models.ipynb
0019-MCAL-margin_calculator.md
0020-APIS-core_api.md
0021-MDAT-market_data_spec.md
0023-CALI-calibrators.md
0024-OSTA-order_status.md
0025-OCRE-order_submission.md
0026-AUCT-auctions.md
0027-ASSP-asset_proposal.md
0028-GOVE-governance.md
0029-FEES-fees.md
0030-ETHM-multisig_control_spec.md
0031-ETHB-ethereum_bridge_spec.md
0032-PRIM-price_monitoring.md
0033-OCAN-cancel_orders.md
0034-AUTH-auth.md
0035-LIQM-liquidity_monitoring.md
0035-prob-weighted-liquidity-measure.ipynb
0036-BRIE-event_queue.md
0037-OPEG-pegged_orders.md
0038-OLIQ-_liquidity_provision_order_type.md
0039-MKTD-market_depth_calculation.md
0040-ASSF-asset_framework.md
0041-TSTK-target_stake.md
0042-LIQF-setting_fees_and_rewarding_lps.md
0043-market-lifecycle-flow-diagram.graffle
0043-market-lifecycle-flow-diagram.svg
0043-MKTL-market_lifecycle.md
0044-LIQM-lp_mechanics.md
0045-DSRC-data_sourcing.md
0046-DSRM-data_source_signed_message.md
0047-DSRF-data_source_filter.md
0048-DSRI-data_source_internal.md
0049-TVAL-validate_transaction_preconsensus.md
0050-EPOC-epochs.md
0051-PROD-product.md
0052-FPOS-fractional_orders_positions.md
0053-PERP-product_builtin_perpetual_future.md
0054-NETP-network_parameters.md
0055-on-chain-treasury-draft-sketch.jpg
0055-TREA-on_chain_treasury.md
0056-REWA-rewards_overview.md
0057-REWF-reward_functions.md
0058-REWS-simple_POS_rewards.md
0059-STKG-simple_staking_and_delegating.md
0060-WENDY-wendy.md
0061-REWP-simple_pos_rewards_sweetwater.md
0062-SPAM-spam_protection.md
0063-VALK-validator_vega_master_keys.md
0064-VALP-validator_performance_based_rewards.md
0065-FTCO-floating_point_consensus.md
0065-VALW-validator_tendermint_weights.md
0066-KEYS-key_management.md
```

**Comment by witgaw** [comment]
Please note `0035-prob-weighted-liquidity-measure.ipynb` (or 0034 in old money) is a spec in it's own right (not an appendix of sorts like some of the figures). It's got a different extension which seems to be causing some problems.

**Comment by davidsiska-vega** [comment]
Other than what @witgaw pointed out - I like the 4 letter acronyms a lot.

**Comment by edd** [comment]
So here's the final output. I've also added a makefile that will verify it, but **I am bad at makefiles**, so I'd love someone else to improve it. I'll add a new ticket for that.

`make numbers` - shows a message if there are no duplicate numeric IDs
`make names` - shows a message if there are `.md` or `.ipynb` files are named badly. SVGs/PNGs/Graffles can be named whatever
`make show-numbers` - shows which numbers are duplicate

Who are show-numbers and numbers separate? Because I'm not good at makefiles. But hey, it's useful! Anyway:


```
0001-MKTF-market_framework.md
0002-STTL-settlement.md
0003-MTMK-mark_to_market_settlement.md
0004-AMND-amends.md
0005-COLL-collateral.md
0006-POSI-positions_core.md
0007-POSN-non_core_positions_api.md
0008-TRAD-trading_workflow.md
0009-MRKP-mark_price.md
0010-MARG-margin_orchestration.md
0011-MARA-check_order_allocate_margin.md
0012-POSR-position_resolution.md
0013-ACCT-accounts.md
0014-ORDT-order_types.md
0015-INSR-market_insurance_pool_collateral.md
0016-PFUT-product_builtin_future.md
0017-PART-party.md
0018-RSKM-quant_risk_models.ipynb
0019-MCAL-margin_calculator.md
0020-APIS-core_api.md
0021-MDAT-market_data_spec.md
0022-AUTH-auth.md
0023-CALI-calibrators.md
0024-OSTA-order_status.md
0025-OCRE-order_submission.md
0026-AUCT-auctions.md
0027-ASSP-asset_proposal.md
0028-GOVE-governance.md
0029-FEES-fees.md
0030-ETHM-multisig_control_spec.md
0031-ETHB-ethereum_bridge_spec.md
0032-PRIM-price_monitoring.md
0033-OCAN-cancel_orders.md
0034-PROB-prob_weighted_liquidity_measure.ipynb
0035-LIQM-liquidity_monitoring.md
0036-BRIE-event_queue.md
0037-OPEG-pegged_orders.md
0038-OLIQ-liquidity_provision_order_type.md
0039-MKTD-market_depth_calculation.md
0040-ASSF-asset_framework.md
0041-TSTK-target_stake.md
0042-LIQF-setting_fees_and_rewarding_lps.md
0043-market-lifecycle-flow-diagram.graffle
0043-market-lifecycle-flow-diagram.svg
0043-MKTL-market_lifecycle.md
0044-LIQM-lp_mechanics.md
0045-DSRC-data_sourcing.md
0046-DSRM-data_source_signed_message.md
0047-DSRF-data_source_filter.md
0048-DSRI-data_source_internal.md
0049-TVAL-validate_transaction_preconsensus.md
0050-EPOC-epochs.md
0051-PROD-product.md
0052-FPOS-fractional_orders_positions.md
0053-PERP-product_builtin_perpetual_future.md
0054-NETP-network_parameters.md
0055-on-chain-treasury-draft-sketch.jpg
0055-TREA-on_chain_treasury.md
0056-REWA-rewards_overview.md
0057-REWF-reward_functions.md
0058-REWS-simple_pos_rewards.md
0059-STKG-simple_staking_and_delegating.md
0060-WEND-wendy.md
0061-REWP-simple_pos_rewards_sweetwater.md
0062-SPAM-spam_protection.md
0063-VALK-validator_vega_master_keys.md
0064-VALP-validator_performance_based_rewards.md
0065-FTCO-floating_point_consensus.md
0066-VALW-validator_tendermint_weights.md
0067-KEYS-key_management.md
```

**Pull request merged**
