### PR TITLE
Updated market lifecycle diagram

### PR DESCRIPTION
**Pull request by campbellssource**
Updated To:
0029-market-lifecycle-flow-diagram

Previous:
Screenshot 2021-03-05 at 10 48 19

Also changed file number to be the same as spec.

### CODE REVIEW

**Comment by tamlyn10** [comment]
@campbellssource thanks for this! Btw you can also get to "Cancelled" state from a governance vote to close the market.

**Comment by tamlyn10** [comment]
Also, the "maturity event" isn't quite the trigger for the "Trading Terminated".. the table says:

> Defined by the product (i.e. from a product parameter, specified in market definition, giving close date/time)

**Comment by edd** [comment]
> @campbellssource thanks for this! Btw you can also get to "Cancelled" state from a governance vote to close the market.

You *should* be able to. But I don't think this is implemented. Which is an oversight:

https://github.com/vegaprotocol/vega/blob/8fb63848073fac5c7bbd31ab2af8eedcb1b636b8/gateway/graphql/schema.graphql#L1967-L1976

https://github.com/vegaprotocol/vega/blob/8fb63848073fac5c7bbd31ab2af8eedcb1b636b8/proto/governance.proto#L88

**Comment by campbellssource** [comment]
Guilty of raising the PR a little early. Will make it a draft and revise

**Comment by campbellssource** [comment]
To much to rebase, just going to create a fresh branch

**Pull request closed without merging**
